# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable-all: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-checks:
      - nilValReturn

linters:
  enable:
    - revive
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports
    - gosimple
    - unused
    - staticcheck # enable before push
    - gocyclo
    - dupl
    - gocognit
    - prealloc
    - perfsprint
    - gochecknoinits
    - wsl
    - gocritic
    - wastedassign
    - misspell

issues:
  exclude:
    - fieldalignment
    - G115
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - gosec
        - errcheck
        - dupl
        - perfsprint
    - path: mock.go
      linters:
        - gosec
