version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - dupl
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - perfsprint
    - prealloc
    - revive
    - wastedassign
    - wsl
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-checks:
        - nilValReturn
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocognit
          - gocyclo
          - gosec
          - perfsprint
        path: _test\.go
      - linters:
          - gosec
        path: mock.go
      - linters:
          - govet
        text: fieldalignment
      - linters:
          - gosec
        text: "G115:"
      - linters:
          - staticcheck
        text: "QF1008:"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
